[SEASK-63] Quick Start -> View Reports -> Excel Reports
Ed-Fi-Alliance-OSS/Starter-Kit-SEA-Data-Collection pull request #28
Opened 2021-06-04 14:15 UTC by raghuramakrishna

2021-06-07 14:11 UTC, tbmeador-dlp requested changes

2021-06-07 14:11 UTC, tmeador-dl commented on packer/scripts/report-setup.ps1
> +Invoke-Sqlcmd -Database "EdFi_Ods_2022" -InputFile "C:/sample-reports/2110-CreateProcedureLoadSpedChildCount.sql"
Looks like you've removed all these files so the VM fails when it tries to run these

2021-06-07 14:11 UTC, tmeador-dl commented on packer/sea-starter-kit-win2019-eval.pkr.hcl
> +        "./report.ps1"
```suggestion
      "Set-Location c:/temp/${var.archive_name}/",
      "./report-setup.ps1",
      "Set-Location c:/${var.sample_report}",
      "./report.ps1"
```

2021-06-07 15:24 UTC, raghuramakrishna commented on packer/sea-starter-kit-win2019-eval.pkr.hcl
> +        "./report.ps1"
done

2021-06-08 19:48 UTC, tbmeador-dlp approved these changes

2021-06-08 19:53 UTC, merged