[SEASK-62] Quick Start -> Automated VM Set Up -> Reporting Queries & Validation Queries
Ed-Fi-Alliance-OSS/Starter-Kit-SEA-Data-Collection pull request #30
Opened 2021-06-09 12:46 UTC by raghuramakrishna

2021-06-09 21:50 UTC, tbmeador-dlp requested changes
everything looks good just one minor change

2021-06-09 21:50 UTC, tmeador-dl commented on packer/sea-starter-kit-win2019-eval.pkr.hcl
> +      "Copy-Item ./${var.sample_validation}/* ./${var.databases}/Ed-Fi-ODS-Implementation/Artifacts/MsSql/Structure/Ods/ -filter '*.sql' -recurse"
```suggestion
      "Copy-Item ./${var.sample_validation}/* ./${var.databases}/Ed-Fi-ODS-Implementation/Artifacts/MsSql/Structure/Ods/ -filter '*.sql' -recurse",
```

2021-06-10 07:54 UTC, raghuramakrishna commented on packer/sea-starter-kit-win2019-eval.pkr.hcl
> +      "Copy-Item ./${var.sample_validation}/* ./${var.databases}/Ed-Fi-ODS-Implementation/Artifacts/MsSql/Structure/Ods/ -filter '*.sql' -recurse"
updated

2021-06-10 17:13 UTC, tbmeador-dlp approved these changes

2021-06-10 17:13 UTC, merged