Seask 44
Ed-Fi-Alliance-OSS/Starter-Kit-SEA-Data-Collection pull request #6
Opened 2021-05-03 18:27 UTC by markramonDL

Two additional districts created to support use cases in:

https://techdocs.ed-fi.org/display/SKD/SEA+Starter+Kit+-+Membership+%3D+Student+Count+in+AZ+Use+Case
https://techdocs.ed-fi.org/display/SKD/SEA+Starter+Kit+-+Special+Education+Student+Count+Use+Case

changed sample XML files:

EducationOrganization.xml
Student.xml
StudentEnrollment.xml
StudentProgram.xml

2021-05-03 18:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Ed-Fi-Alliance-OSS/Starter-Kit-SEA-Data-Collection?pullRequest=6) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Ed-Fi-Alliance-OSS/Starter-Kit-SEA-Data-Collection?pullRequest=6) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Ed-Fi-Alliance-OSS/Starter-Kit-SEA-Data-Collection?pullRequest=6) it.</sub>

2021-05-05 19:48 UTC, blmeyers requested changes
This might be easier to manage if we break up the xml files based on the district, rather than combining both new districts into a single file.  The only exception might be EducationOrganization.xml, since that sort of spans the two with some shared components.

Load Errors
Local Education Agency Bear Creek ISD has space at end of StreetNumberName
Student 704950 -> Reference to Person 704950 that doesn't exist
Student 705183 -> Reference to Person 705183 that doesn't exist
Student 705362 -> Reference to Person 705362 that doesn't exist
Student 805362 -> Reference to Person 805362 that doesn't exist
Student 805704 -> Reference to Person 805704 that doesn't exist
Student 705704 -> Two xml elements with this student id
Student 705705 -> Two xml elements with this student id
Student 805805 -> Two xml elements with this student id

After that due to one of the LEAs not loading there was too much noise to get more errors our.  Will need to be run through again after fixing these issues.

2021-05-05 19:48 UTC, blmeyers commented on sample-data/Samples/Sample XML/EducationOrganization.xml
> +				<TelephoneNumber>(512) 494-1213</TelephoneNumber>
If you check Grand Bend, you'll see the phone numbers were changed to the 950 area code instead of 512.  This area code isn't assigned so any numbers in it aren't real, so works well for sample data rather than including real phone numbers, even if those real phone numbers are likely public information.

2021-05-05 19:48 UTC, blmeyers commented on sample-data/Samples/Sample XML/EducationOrganization.xml
> +			<StreetNumberName>202 Maple Street </StreetNumberName>
```suggestion
			<StreetNumberName>202 Maple Street</StreetNumberName>
```

2021-05-05 19:48 UTC, blmeyers commented on sample-data/Samples/Sample XML/EducationOrganization.xml
> +			<IndicatorGroup>uri://gbisd.edu/IndicatorGroupDescriptor#Staff Indicator</IndicatorGroup>
As discussed, make sure we're using the new district specific namespaced descriptor values for these.

2021-05-05 19:48 UTC, blmeyers commented on sample-data/Samples/Sample XML/EducationOrganization.xml
> +			<IndicatorGroup>uri://gbisd.edu/IndicatorGroupDescriptor#Staff Indicator</IndicatorGroup>
As discussed, make sure we're using the new district specific namespaced descriptor values for these.

2021-05-05 19:48 UTC, blmeyers commented on sample-data/Samples/Sample XML/EducationOrganization.xml
> +			<IndicatorGroup>uri://gbisd.edu/IndicatorGroupDescriptor#Staff Indicator</IndicatorGroup>
As discussed, make sure we're using the new district specific namespaced descriptor values for these.

2021-05-05 19:48 UTC, blmeyers commented on sample-data/Samples/Sample XML/EducationOrganization.xml
> +			<IndicatorGroup>uri://gbisd.edu/IndicatorGroupDescriptor#Staff Indicator</IndicatorGroup>
As discussed, make sure we're using the new district specific namespaced descriptor values for these.

2021-05-05 19:48 UTC, blmeyers commented on sample-data/Samples/Sample XML/EducationOrganization.xml
> +			<IndicatorGroup>uri://gbisd.edu/IndicatorGroupDescriptor#Staff Indicator</IndicatorGroup>
As discussed, make sure we're using the new district specific namespaced descriptor values for these.

2021-05-05 19:48 UTC, blmeyers commented on sample-data/Samples/Sample XML/EducationOrganization.xml
> +		<NameOfInstitution>Communities in Schools</NameOfInstitution>
Do we need some way to differentiate the CommunityOrganizations other than the id?  They're all named "Communities in Schools" including the Grand Bend one.

2021-05-05 19:48 UTC, blmeyers commented on sample-data/Samples/Sample XML/EducationOrganization.xml
> +		<NameOfInstitution>Communities in Schools</NameOfInstitution>
Note also from a data model perspective, there isn't necessarily one of these per district (or even one CommunityProvider per district) which is why they're separate in the org hierarchy.

2021-05-05 19:48 UTC, blmeyers commented on sample-data/Samples/Sample XML/EducationOrganization.xml
> +	<PostSecondaryInstitution>
Not sure we even need any new PostSecondaryInstitutions, since this won't be impacted by the State use case.

2021-05-05 19:48 UTC, blmeyers commented on sample-data/Samples/Sample XML/EducationOrganization.xml
> +		<NameOfInstitution>Communities in Schools</NameOfInstitution>
So as an alternative, maybe we just don't make any new community organization/community provider/community provider license entities for this sample data set? @vimayya

2021-05-05 19:48 UTC, blmeyers commented on sample-data/Samples/Sample XML/EducationOrganization.xml
> +			<StreetNumberName>202 Maple Street </StreetNumberName>
"Validation of 'LocalEducationAgency' failed.\r\n\tValidation of 'EducationOrganizationAddresses' failed.\n\t\tEducationOrganizationAddress[0]: StreetNumberName property is part of the primary key and therefore its value cannot contain leading or trailing whitespace."

2021-05-05 19:48 UTC, blmeyers commented on sample-data/Samples/Sample XML/EducationOrganization.xml
> +			<Indicator>uri://lisd.edu/IndicatorDescriptor#Retention Rate</Indicator>
Need a separate file to load these new descriptor values, since they're district specific.  See descriptor files at https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-Standard/tree/main/Samples/Sample%20XML.

2021-05-07 18:51 UTC, blmeyers approved these changes

2021-05-07 18:51 UTC, blmeyers commented
Made adjustments for everything I was concerned on, and got the xml files all loading without error.  Needs review by another team member.

2021-05-10 13:03 UTC, blmeyers commented
Updated based on the work in SEASK-45, with updates to that security on the end.

2021-05-10 13:14 UTC, blmeyers commented
Clean build loading the data at https://intedfitools1.msdf.org/buildConfiguration/OdsPlatform_OdsApi_Packages_EdFiOdsPopulatedTemplateSk/129618

2021-05-10 14:10 UTC, jamessmckay approved these changes

2021-05-10 14:11 UTC, merged