ODS-5560 Packages - EdFi.Ods.Populated.Template.SK workflow added
Ed-Fi-Alliance-OSS/Starter-Kit-SEA-Data-Collection pull request #63
Opened 2022-12-06 04:36 UTC by semalaiappan

2022-12-06 14:18 UTC, semalaiappan commented
EdFi.Ods.Populated.Template.SK Github build Records: 243987 matches with Teamcity buid Records: 243987

2022-12-12 15:40 UTC, bptillman requested changes
The template built here looks correct so the build itself is good. Just one minor change and one question I had and once those are resolved this should be good to go.

2022-12-12 15:40 UTC, bptillman commented on .github/workflows/Packages - EdFi.Ods.Populated.Template.SK.yml
> +        .\build.githubactions.ps1 pack -Configuration ${{ env.CONFIGURATION }} -InformationalVersion ${{ env.INFORMATIONAL_VERSION }} -BuildCounter ${{ github.run_number }} -BuildIncrementer ${{env.B
Please switch from using blackslashes to forward slashes in the path to the nuspec file parameter here.

2022-12-12 15:40 UTC, bptillman commented on .github/workflows/Packages - EdFi.Ods.Populated.Template.SK.yml
> +  INFORMATIONAL_VERSION: "7.0"
Do we know why the builds in TeamCity were done with version 1.0.x? Changing this to 7.0.x makes sense but I was curious if there was a reasoning this package ended up with such a different version number scheme.

2022-12-13 14:25 UTC, semalaiappan commented on .github/workflows/Packages - EdFi.Ods.Populated.Template.SK.yml
> +        .\build.githubactions.ps1 pack -Configuration ${{ env.CONFIGURATION }} -InformationalVersion ${{ env.INFORMATIONAL_VERSION }} -BuildCounter ${{ github.run_number }} -BuildIncrementer ${{env.B
Fixed it . Thanks

2022-12-13 14:26 UTC, semalaiappan commented on .github/workflows/Packages - EdFi.Ods.Populated.Template.SK.yml
> +  INFORMATIONAL_VERSION: "7.0"
Moved back to 1.1.X after discussing with Vinaya on this

2022-12-13 16:41 UTC, semalaiappan commented on .github/workflows/Packages - EdFi.Ods.Extensions.SK.yml
> -  pull_request:
I removed here because we are not running pull request for any other templates also

2022-12-13 17:23 UTC, bptillman approved these changes

2022-12-13 17:24 UTC, merged